services:
  backend:
    build:
      context: ./backend
    container_name: telcox-backend
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./backend:/app